default:
  image:
    name: rust:1.42.0
  tags:
    - shared-exec-docker

stages:
  - check
  - assets
  - build

rust_fmt:
  stage: check
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt -- --check

yarn:
  stage: assets
  image: node:alpine
  before_script:
    - apk add make
  script:
    - make deps
  artifacts:
    expire_in: 1 hour
    paths:
      - assets/web/vendor

compile:
  stage: build
  script:
    - cargo build