default:
  image:
    name: rust:1.42.0
  tags:
    - shared-exec-docker

stages:
  - assets
  - test

yarn:
  stage: assets
  image: node:alpine
  script:
    - yarn install --modules-folder assets/web/vendor
  artifacts:
    expire_in: 1 hour
    paths:
      - assets/web/vendor

rust_fmt:
  stage: check
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt -- --check

compile:
  stage: build
  script:
    - cargo build