default:
  image:
    name: rust:1.42.0
  tags:
    - shared-exec-docker

stages:
  - assets
  - test
  - publish

yarn:
  stage: assets
  image: node:alpine
  script:
    - yarn install --modules-folder assets/web/vendor
  artifacts:
    expire_in: 1 hour
    paths:
      - assets/web/vendor

cargo fmt:
  stage: test
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt -- --check

cargo test:
  stage: test
  script:
    - cargo test

compile:
  stage: test
  script:
    - cargo build

publish dry run:
  stage: test
  image: rust
  before_script:
    - cargo login $CRATES_IO_TOKEN
  script:
    - cargo publish --dry-run --allow-dirty

crates.io:
  stage: publish
  before_script:
    - cargo login $CRATES_IO_TOKEN
  script:
    - cargo publish --allow-dirty
  only:
    refs:
      - master